### ISSUE TITLE
Error when launching version 0.2.2

### ISSUE THREAD

**Issue by KoRnBoy82** [komefai/PS4Macro#1]
When launching the exe (without RemotePlay actually opened), there is an "Unhandled" error with MainForm.cs at line 68. Reference is not defined to an object.

System.NullReferenceException

But it's working if you open it after launching the remote play app.

**Comment by komefai** [comment]
Hi, thanks for the report! I actually made a mistake and realized it after the release of v0.2.2. The bug has been fixed on [this commit](https://github.com/komefai/PS4Macro/commit/9b69925c2d73ae5a0b4e2681fa4d6590329437a0) and will be officially released with the next version instead (very soon).

I will attach the latest commit build here just in case.
[PS4Macro_022_2d1b808.zip](https://github.com/komefai/PS4Macro/files/1296468/PS4Macro_022_2d1b808.zip)

**Comment by KoRnBoy82** [comment]
Thanks :) I will test this really hard starting from now on ;)
