### ISSUE TITLE
[Enhance] Integrate OCR to PS4Macro API

### ISSUE THREAD

**Issue by leguims** [komefai/PS4Macro#11]
It could be usefull to integrate [Tesseract](https://github.com/tesseract-ocr/tesseract/wiki) to method MatchTemplate.

You already have PixelMap and RectMap to call it. I'd like to have a new type "TextMap" to call it. This one would use Tesseract.

```
namespace PS4MacroAPI
{
    public struct TextMap
    {
        public string ID { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public string Text { get; set; }
    }
}
```

**Comment by leguims** [comment]
I think this would be more efficient for [PS4Macro.PES2018Lite](https://github.com/leguims/PS4Macro.PES2018Lite) to look for text instead of compare images.

Resources:

- [OCR using Tesseract in C#](http://www.c-sharpcorner.com/article/ocr-using-tesseract-in-C-Sharp/)
 - [How to implement and do OCR in a C# project?](https://stackoverflow.com/questions/10947399/how-to-implement-and-do-ocr-in-a-c-sharp-project)

**Comment by clempe** [comment]
I would disagree with your statement. By using OCR you have to do even more calculations. You have to take the screenshot, process the the image and predict a nonce.

**Comment by leguims** [comment]
By "more efficient" I meaned "more customable" (FRA to ENG will be easier with configuration file) and "more accuracy". But you're right Clempe, it will be more process greedy.

**Comment by komefai** [comment]
Thanks for the suggestion @leguims, but I have to agree with @clempe on this one. Tesseract also requires the training data and can be really huge when supporting many languages. I think that a better pattern would be to host a library (eg. PS4MacroAPI.Tesseract) on Nuget so it can be add/update on demand instead of being built-in to the API.
