### ISSUE TITLE
Build error about easyload32.dll

### ISSUE THREAD

**Issue by ATGx97** [komefai/PS4Macro#15]
Every time I try to build it it errors saying the easyload32.dll is locked by ps4 remote play and that it fails to copy easyload32.dll to bin\debug\EasyLoad32.dll because it cannot be accessed as it's being used by another process

**Comment by ATGx97** [comment]
Also an error about easy hook version 2.7.0 or whatever not matching the assembly. I've tried reinstalling all the nuget plugins and changing the easy hook version but nothing worked. Also should I have it on debug or release?

**Comment by komefai** [comment]
That's strange, how can it be locked by another process if it never gets build? What version of visual studio are you using, and if possible please include the error or a screenshot.

> Also should I have it on debug or release?

Use debug build configuration
