### ISSUE TITLE
How can i use My DS3 Controller with this, which is already emulated as Xbox360 Controller

### ISSUE THREAD

**Issue by Kristijan1001** [komefai/PS4Macro#16]
I am wondering what would be the way to use DS3 controller with this program, also wanna ask one question, Is the macro noticeable or does it just recognize it as controller, cause i want to try using it in Destiny 2 and don't wanna get banned for it :) . 

I wonder if there is ready to go xml file that emulates xbox 360

also sorry if i shouldnt have posted this here , dunno where else to ask for help. Thank You

**Comment by komefai** [comment]
Hi, there are no support for other controllers at the moment other than DS4 via USB (or [emulated DS4](https://github.com/komefai/PS4Macro#settings)). It could be a good addition to the Remapper so I might implement this feature in the future.

> Is the macro noticeable or does it just recognize it as controller, cause i want to try using it in Destiny 2 and don't wanna get banned for it :) .

PS4 Macro intercepts the controller inputs from Remote Play emulating the data of the real DS4 controller. Which means that the macro is undetectable to the game. However, some games (especially online) can detect botting activities so you still have to be careful.
