### ISSUE TITLE
Simple Remapper button press not working

### ISSUE THREAD

**Issue by e-volusian** [komefai/PS4Macro#17]
Hi, I'm having difficulty with the Remapper.

Just as a simple test case, I was trying to hit the Triangle button:

1. Launch PS4 Remote Play
2.  Launch PS4 Macro
3.  Open Tools > Remapper (notice that Triangle is mapped to V)
4.  Focus PS4 Remote Play
5.  Press V
6. (Nothing happens)

I attempted to troubleshoot this with a `settings.xml` which included `<ShowConsole>true</ShowConsole>`. After restarting everything, the debugging console is launched but nothing is printed therein.

Any ideas? Am I missing something?

Important notes:
* At this time, I am **not** using a controller
* This is on Windows 10 Pro running on VirtualBox on Windows 7 (PS4 Remote Play does not work on Windows 7 directly)
* The macro functionality also seems to not work
* Screen resize does work

**Comment by e-volusian** [comment]
I thought more about it, and realized it might be unrealistic to expect functionality within a virtual machine. Both this project and VirtualBox seem to use some kind of "low-level keyboard hooks" so there might be a conflict.

I'm going to try on bare metal.

**Comment by Y-T-G** [comment]
Did you try this build with Status Checker ?https://github.com/komefai/PS4Macro/files/1734519/PS4Macro_c43db4.zip
Post a screenshot of the Status Checker (Help>Status Checker) window after starting up PS4Macro.

**Comment by e-volusian** [comment]
Previously I was using the latest release (PS4Macro_0_5_2)

Using the linked file ...b4.zip I get this message:

![image](https://user-images.githubusercontent.com/7467373/36882434-7bba03a8-1d99-11e8-9ce4-1aad4d23337a.png)

**Comment by Y-T-G** [comment]
@e-volusian Do you get a 'Working' status for Interceptor if you connect a DS4 to your PC?

**Comment by e-volusian** [comment]
@Y-T-G  -- I moved off the VirtualBox virtual machine and installed everything on a fresh copy of Windows 10 Home. That did not change the behavior (the Status Checker still shows _Interceptor: Not Working_

Plugging in a DualShock controller into the laptop's USB port also has no effect. Nothing changes in PS4Macro.

Is the expectation that I should be able to plug the DS4 into my laptop and then control the PS4 Remote Play window? Because that doesn't work either.

**Comment by e-volusian** [comment]
p.s. The only thing that changed is that the debugging Window does output something now. It was totally blank before.

![image](https://user-images.githubusercontent.com/7467373/37470721-25a44b3e-2836-11e8-9c31-67c92cafbf04.png)

**Comment by e-volusian** [comment]
Update: I was able to get the DS4 working over USB after installing [DS4Windows](https://github.com/Jays2Kings/DS4Windows/releases) and also changing the USB cable. I did these both at the same time so I don't know which one solved the problem.

No change to _Interceptor: Not Working_ though.

**Comment by Y-T-G** [comment]
@e-volusian Does your PS4 Remote Play screen look like this when you connect DS4 with USB to your PC:
![image](https://user-images.githubusercontent.com/32206511/37477325-d58fd6d0-2890-11e8-8178-22e8a5018c0a.png)
If not, there is some problem with drivers.

**Comment by e-volusian** [comment]
@Y-T-G Yes my screen looks like that. The controller works now but still no interceptor. Thanks for your help

If settings.xml has AutoInject=false, is there some manual step that I need to perform?

![image](https://user-images.githubusercontent.com/7467373/37478177-8946807e-2847-11e8-8826-8372bfdfc61a.png)

**Comment by Y-T-G** [comment]
This is how mine looks like:
![image](https://user-images.githubusercontent.com/32206511/37478957-e0aafa96-2894-11e8-95ee-051e6e58ffbc.png)
Did you try running it as administrator?

**Comment by e-volusian** [comment]
No change with Run as Administrator

![image](https://user-images.githubusercontent.com/7467373/37480627-b6b62644-284d-11e8-98d4-d8072f981e78.png)

My driver info is below. The only way I could get the controller working was by using DS4Windows which emulates an Xbox 360 controller. However, my driver version number is almost exactly the same as yours (10.0.16299.251 vs 10.0.16299.250) which makes me think it's actually the same driver.

![image](https://user-images.githubusercontent.com/7467373/37480758-14e91dc0-284e-11e8-8a7e-44beff93c809.png)

**Comment by e-volusian** [comment]
Ok, it seems to be working now, using the latest release and with no settings.xml. 

I'm not sure what happened, but thanks again for helping me get it working @Y-T-G

**Comment by Y-T-G** [comment]
@e-volusian Nice. Post a screenshot though of Status Checker now that you have it working.

**Comment by e-volusian** [comment]
Here it is. I'm having some problems with recorded macros being played back reliably, but I'll deal with that separately.

![image](https://user-images.githubusercontent.com/7467373/37487415-7aa9c28e-285f-11e8-9221-64777dbf8ab2.png)

**Comment by Y-T-G** [comment]
@e-volusian Are you able to use Remapper with `EmulateController`   `false`?

**Comment by e-volusian** [comment]
> Are you able to use Remapper with EmulateController false?

Yes

**Comment by Y-T-G** [comment]
Hmmm, @komefai is this supposed to happen?

**Comment by komefai** [comment]
I can also confirm that using a VM does work but cannot process the macro data fast enough for ~30fps. If possible, you can try [Scripting](https://github.com/komefai/PS4Macro/wiki) instead of using macros in a VM because it does perform quite well in most cases. If you got EmulatedController to work then it might improve the performance a little bit. I'm running 64-bit Windows 10 VirtualBox (2 CPU cores and 8GB of RAM) on a Windows 10 host by the way.

Normally when you get OnInjectionSuccess message and have the `Press the OPTIONS button on the controller to start.` screen, the interceptor status should work. The only reason I can think of is that PS4 Remote Play detected a hardware controller making it ignore the emulated controller from PS4 Macro. This happened to me quite a few times while developing a feature when I forgot to unplug a DS4 controller while setting EmulateController to true.

@Y-T-G Thanks again for helping out!

**Comment by ArielHashuel** [comment]
settings.xml

<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <AutoInject>false</AutoInject>
  <BypassInjection>false</BypassInjection>
  <EmulateController>true</EmulateController>
  <ShowConsole>false</ShowConsole>
  <StartupFile>MyMacro.xml</StartupFile>
</Settings>

**Comment by Albertloo** [comment]
I may have found a solution that works for me after many tries - from switching wifi to ethernet / updating windows, drivers / switching usb ports / the list goes on.. and the solid solution is to put PS4 Macro, the whole folder into a different drive. 

My 1st PC works flawlessly (both PS4 Remote Play and PS4 Macro in drive C). It's when I duplicated the setup to my 2nd PC that was when problem occurs - the macro either play very slowly , not playing at all, and the Interceptor status check not working (out of many tries, it work once..) or sometimes the Interceptor status works but as soon as I move the mouse, it shows Not Working.

But as soon as I move the PS4 Macro into drive D:  it works flawlessly like my 1st PC. (My 2nd PC is running 4 SSDs - Drive C,D,E and F). Perhaps bandwidth issue  ?
