### ISSUE TITLE
Not an issuse but a question about the app 

### ISSUE THREAD

**Issue by Kristijan1001** [komefai/PS4Macro#19]
Hello , the app is great uve done good job on it, i am trying to use it in Destiny 2, but i am not good with C# at all , what i would want is a script that randomizes certain buttons and sticks so it never does the same commands over and over again. Also wanna ask if its possible to create a script where it has for example no recoil for some guns. I know crounsmax can do this and there are alot of scripts for it. But since i dont have one this is the closest thing to it. Would been Nice if this program had like a site where users can share scripts to help noobs like me cause i have no idea how to code in C.

I watched all of ur yt tutorials , do u think it would be possible to make a bot for destiny 2  ? or would that be really complicated ? I also heard you say u can make aimbots is that even possible in destiny 2 ?

Thank you for your time .

**Comment by komefai** [comment]
Thanks for the kind words!

> a script that randomizes certain buttons and sticks so it never does the same commands over and over again

That is possible to do and not difficult at all. Here's a simple script to press a control randomly every second:

```csharp
using PS4MacroAPI;

public class Script : ScriptBase
{
    // List to store the random states
    List<DualShockState> RandomStates { get; set; }

    /* Constructor */
    public Script()
    {
        Config.Name = "Example Script";

        // Update every one second
        Config.LoopDelay = 1000;

        // Create all possible states
        RandomStates = new List<DualShockState>()
        {
            new DualShockState({Cross = true}),
            new DualShockState({R2 = 255});
            new DualShockState({DPad_Up = true});
            new DualShockState({LX = 0});
            new DualShockState({Square = true});

            // etc..
        };
    }

    // Called when the user pressed play
    public override void Start()
    {

    }

    // Called every interval set by LoopDelay
    public override void Update()
    {
        Random rnd = new Random();

        // Fetch one of the states randomly
        var randomIndex = rnd.Next(RandomStates.count);
        var theRandomState = RandomStates[randomIndex];

        // Apply the state
        script.Press(theRandomState);
    }
}
```

> Also wanna ask if its possible to create a script where it has for example no recoil for some guns

Hmm.. I'm not sure what you mean by this. Can you give me a link to a video of it?

> Would been Nice if this program had like a site where users can share scripts to help noobs like me cause i have no idea how to code in C.

I would like the have a website for that as well, right now the [PS4 Macro website](http://ps4macro.com) is redirecting to this GitHub page, but I plan to host the scripts and guides there in the future.

> I watched all of ur yt tutorials , do u think it would be possible to make a bot for destiny 2 ? or would that be really complicated ? I also heard you say u can make aimbots is that even possible in destiny 2 ?

Thank you! It is possible to make a bot for Destiny 2 and other first person shooting games, but developing and perfecting it would not be an easy task. Specifically, to make an aimbot using purely visuals from the game, you would have to have a decent understanding of machine learning and AI. If you're interested you can read the blog post from OpenAI on making a Dota 2 bot as an example [here](https://blog.openai.com/dota-2/).

**Comment by Kristijan1001** [comment]
What i meant for no recoil is , for example when u shoot a gun in destiny the gun goes up, so u have to hold the right stick abit down so it the cross hair doesnt go to the sky. So basicly what should be done or how i think it would be, everytime u shoot the program normalizes the recoil automaticly, so u dont have to control the recoil at all.

As for the the random buttons code thanks alot for that and ur time, i should have mention i want every button to be pressed on diffrent time interval so its not always for example 5seconds only, but sometimes for example 5,6,7. etc.

If you dont mind if u could make one where it presses every button except: circle,pause,share button,touchpad . But presses all the rest of the buttons randomly in random time intervals, and some of them getting hold for random time. For example one time it holds forward on the stick for few seconds, or holds R2 for few seconds. So its just not always pressing it for a quick second and moving to the next command, or just spamming 20000 buttons in 20seconds.

So:
-Exclude: Circle, Pause, Share Button, Touchpad.
-Random Timing Interval Between Button Presses (>=5<=10 Time between buttons should never be below 5 Seconds so it Doesn't get spammy)
-Random Time Holding the Button (>=5<=10)
-Possibility of having <=3 Buttons pressed at the same time. (Example having L2 Pressed to initiate aiming and having R2 Pressed to initiate Shooting,L3 for running, But this can be completly random every time, for example sometimes would be runing and couching or running and jumpin. etc. endless combos)

How would look like in game 3 way combo:
runs for 5 seconds, while it shoots for 6 seconds , while holding the aim button for 7 seconds
This is just an example ^ can be with any random button doesnt matter.

Eitherway thats what i thought of it how would be done, I really don't understand coding so have no idea how would this work out or if its easy or not.

If it's easy and you have the time and don't mind doing would appreciate it alot, if not its fine. 

Thanks alot again.

**Comment by komefai** [comment]
I see what you mean now! However, I don't really have time to code on a complex script right now so I guess that the next best way is to record a long macro and repeat it in a loop instead. If I have the time I will definitely make a more general purpose script that will support your requirements and release it to the public :D
