### ISSUE TITLE
DS4 Touchpad left and right press remapping

### ISSUE THREAD

**Issue by starboy76** [komefai/PS4Macro#25]
Thank you for sharing this project. I've search for something like this for a while.

Am I correct that it's not possible to remap a left or right touchpad press? I can't start PS2 games on remote play without a right press on the touchpad.

Regardless, great work.

**Comment by komefai** [comment]
Thanks for the kind words! Unfortunately, touchpad remapping is currently limited to just a simple "touch" on the button. The best workaround for that is to record a short macro of the left/right touchpad pressed and then assign it to the remapper as a key instead.

**Comment by starboy76** [comment]
Thank you! Will do that.
