### ISSUE TITLE
Mouse is VERY hard to use

### ISSUE THREAD

**Issue by softwinner360** [komefai/PS4Macro#26]
The mouse is really hard to use. It doesn't work really at all and has really jerked moments, and I can't find any settings that will keep it smooth. What does makeup speed even do?

However I am really proud and exited for this project! Very nice work on this.

**Comment by Y-T-G** [comment]
It is currently in a buggy state and the issue you are experiencing is already known. Please wait for next release. The dev is usually active in weekends, so expect a release soon.
Makeup Speed accelerates the mouse based on its speed.
