### ISSUE TITLE
Remote Play Cannot Detect PS4 Macros Emulated Controller

### ISSUE THREAD

**Issue by ghost** [komefai/PS4Macro#29]
Hi, so I'm trying to get PS4 Macros working on Remote Play on my laptop, and I've been having issues with it getting to properly work with my Remote Play. I've already went over a couple of the issue threads posted here, and I've tried various things to fix this, but in the end I just can't get this working at all. Here's EXACTLY what I did, over and over again:
 
1. I first installed PS4 Macros and extracted it onto my laptop.

2. I then created a new text file inside the PS4 Macros file, naming it "settings.txt", and then copy and pasted these settings:

<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <AutoInject>false</AutoInject>
  <EmulateController>true</EmulateController>
  <ShowConsole>false</ShowConsole>
</Settings>

3. Then I made the txt file into xml file.

4. I FIRST ran Remote Play and after that, instead of hitting the "Start" button on it, I then ran the PS4 Macros application (ran it as administrator).

5. Based on my research from Youtube tutorials and from issue threads here, it should say on the Remote Play "Press option to start" because that's when the Remote Play recognizes the emulator controller, but it doesn't happen for me at all. 

Also note that I've installed the latest updated version of PS4 Macros. 

So I'm not sure what's causing the problem. Did I do something wrong during the entire process? Did I forget to configure something or download something else before doing any of the steps that I mentioned above? I'm not able to use this on my Remote Play at all and I can only use the base controls (enter for X, esc for O, arrows for up, down, right, left). I've also tried configuring the Remapper and such but I just have absolutely no idea how to fix this. I also tried to load xml files in the Macros column of the Remapper (2nd column to the very left at the bottom) but I honestly don't know if that did anything as well. I'm not sure if I've missed something specific here. I've been trying to get this to work for hours but have absolutely no clue how to fix this. I'd appreciate it if anyone can help and advise me to get this to work.

**Comment by komefai** [comment]
Hi, I added a Status Checker window to the unreleased debug build. Please download it from the link below and go to Help->Status Checker to see what is not working.

[PS4Macro_cf7ce2c.zip](https://github.com/komefai/PS4Macro/files/1909931/PS4Macro_cf7ce2c.zip) -[commit [cf7ce2c](https://github.com/komefai/PS4Macro/commit/cf7ce2c4e49301a8d9d225798b499b29b37e41de)]

Closing this issue because it is directly related to: https://github.com/komefai/PS4Macro/issues/8

**Comment by ghost** [comment]
My status checker says "interceptor not working". How do I fix that? Do I need to use DS4 Windows and plug in my PS4 controller to my laptop for DS4 Windows in order for this to work?

**Comment by komefai** [comment]
You don't need DS4 Windows at all. Can you take a screenshot of the Status Checker while PS4 Remote Play is in focus (click Remote Play once to focus it before taking a screenshot).

**Comment by ghost** [comment]
Okay, here
![screenshot 1](https://user-images.githubusercontent.com/38368037/38787670-81fd0f26-40fd-11e8-8241-c17c900a0533.png)


Update: You said that you didn't need a controller in order for this to work right? Well for some reason, when I open up Remote Play, then run the macros on admin, and then plug in my PS4 controller in my laptop via USB and then unplug it, for some reason that gets the interceptor working and I can now completely control my Remote Play screen while I have the remapper open. Is this supposed to happen? This is the only way I can get it to work.
