### ISSUE TITLE
Pressing button

### ISSUE THREAD

**Issue by kdy1029** [komefai/PS4Macro#3]
Hi Komefai. First of all, thank you for your work.
I have a question about pressing buttons. My script works well on my computer, but when it runs on my friend's computer, it sometimes does not pressing a button.
`Press(new DualShockState() { DPad_Up = true }); // always pressing`
`Sleep(1000);`
`Press(new DualShockState() { Square = true }); // sometimes not`
FYI, the loop delay is 3 seconds.
Do you have any idea?

**Comment by komefai** [comment]
Hi! By default the Press() method will hold the button for 150ms and that might be too fast for the game to register the button press. My guess is that the lower the specs, the more imperfect the timing will be. 

To fix the problem, you can try to increase the delay by a few hundred milliseconds to make sure it is long enough for the game to capture it (eg. 300ms).

```csharp
Press(new DualShockState() { DPad_Up = true }, 300);
Sleep(1000);
Press(new DualShockState() { Square = true }, 300);
```

Hope this helps!

**Comment by kdy1029** [comment]
Yes, the key is the timing and increasing the delay makes it happen always. After decreasing the delay, it has been working so far.
Thank you for your help!
