### ISSUE TITLE
Is there a way to map motion controls?

### ISSUE THREAD

**Issue by decastrochad** [komefai/PS4Macro#33]
By motion control, I mean tilting/moving of controller etc that some games require.

**Comment by KaruroHNS** [comment]
@decastrochad 
I think there is no way to remap the Motion Controls yet, you would have to wait for a new update from @komefai

**Comment by komefai** [comment]
That is correct @KaruroHNS . I'm not sure how those will be remapped to primitive interfaces like mouse and keyboard since it requires a 3D space. @decastrochad  The best way you can do now is to pre-record those motions as a Macro and assign it to a hotkey in Remapper instead.
