### ISSUE TITLE
No Mouse check box

### ISSUE THREAD

**Issue by Quinny01** [komefai/PS4Macro#37]
I would like to use my mouse in replacement for my analog stick.  But there isn't a box for me to click as you described?  What am i doing wrong?  Also when do you think the next version of Ps4 Macro will be finished with mouse support?

**Comment by MrDadosz** [comment]
You have to compile new version or use beta version (https://github.com/komefai/PS4Macro/issues/13, https://github.com/komefai/PS4Macro/files/1909931/PS4Macro_cf7ce2c.zip). It's not working  fully correctly right now.
