### ISSUE TITLE
So is this Dead ?

### ISSUE THREAD

**Issue by Kristijan1001** [komefai/PS4Macro#38]
Title

**Comment by Tustin** [comment]
No, it still works just fine and does what it needs to do. I still use it for various games with no issues.

**Comment by Kristijan1001** [comment]
i didnt ask if it works i asked if its dead, it hasnt been updated for a while

**Comment by Tustin** [comment]
My point was it doesn't need updating if everything is working fine with it.

**Comment by KaruroHNS** [comment]
All work fine except the mouse calibration.

**Comment by komefai** [comment]
Hi! I'm just taking a break from this project to work on other personal projects. Definitely not dead, expect to see more updates soon :D
