### ISSUE TITLE
Not compatible in Windows 10? 

### ISSUE THREAD

**Issue by thoastast** [komefai/PS4Macro#39]
![untitled](https://user-images.githubusercontent.com/41006937/42585054-387166a0-8567-11e8-8b35-c632370799cd.png)

Is it not work in Windows 10? Thanks.

**Comment by LaughDonor** [comment]
Works fine for me in Windows 10. Perhaps more details on your configuration?

**Comment by komefai** [comment]
Windows 10 is the environment I used to develop this project so it is supported as a priority. Make sure you download the latest version zip file from the [Releases](https://github.com/komefai/PS4Macro/releases) page and run PS4Macro.exe.

If you still have problems running it feel free to create another issue providing more details on how you set it up.
