### ISSUE TITLE
PS4Macro.remote dll error

### ISSUE THREAD

**Issue by Maurifs** [komefai/PS4Macro#4]
On v0.4.0 I'm getting this error when trying to load the PS4Macro remote dll.
![3jzv6ygg](https://user-images.githubusercontent.com/34663537/34129960-e2626892-e424-11e7-8a4c-90e40e7c5c39.jpg)

**Comment by komefai** [comment]
This problem is caused by a Windows security feature. You can "Unblock" the dll file by `Right Click -> Properties` and then click on Unblock button.

Read more in StackOverflow: https://stackoverflow.com/a/14116631
