### ISSUE TITLE
Disable Looping

### ISSUE THREAD

**Issue by clempe** [komefai/PS4Macro#5]
Is it possible to stop autocalling the update function so that it will only execute once?

**Comment by komefai** [comment]
At the end of your update function you can stop the script like this:

```csharp
// Called every interval set by LoopDelay
public override void Update()
{
    // Your script code ...

    // Stops the script
    this.Host.Stop();
}
```

**Comment by clempe** [comment]
So what happens if `Config.LoopDelay = 800;` and the Update functions takes about 2000 ms?
Will the Update functions start again or will it continue the procedure?

**Comment by komefai** [comment]
In that case, the Update function will take ~2000ms to execute then waits exactly 800ms until it gets called again.

If you're planning to execute it only once then you can ignore Config.LoopDelay completely and assume that Update will get called once because of `this.Host.Stop();` at the end.

**Comment by clempe** [comment]
Thanks that worked
