### ISSUE TITLE
[Tools]->[Screenshot] cannot capture full window

### ISSUE THREAD

**Issue by HyoungWooPark** [komefai/PS4Macro#53]
I click the Screenshot (ctrl+Tab) for saving a screenshot of ps4 remote play, but the wrong cropped image was saved shown below.
![20181028040330825](https://user-images.githubusercontent.com/12387332/47608378-a7699000-da67-11e8-9f92-21f7a94b72dd.png)

**Comment by chanchiem** [comment]
So did you ever find the solution to this?
