### ISSUE TITLE
Cannot save macro after recording it

### ISSUE THREAD

**Issue by clempe** [komefai/PS4Macro#6]
With version 0.5 it's not possible anymore to record an macro and save it (as xml).

![image](https://user-images.githubusercontent.com/491495/34639599-e6c883f4-f2e2-11e7-9123-0720dce4d1ff.png)

**Comment by komefai** [comment]
I'm sorry for that and thank you for reporting! I've release v0.5.1 to fix this problem.

https://github.com/komefai/PS4Macro/releases/tag/v0.5.1
