### ISSUE TITLE
MatchTemplate() throws 'out of memory' exception

### ISSUE THREAD

**Issue by leguims** [komefai/PS4Macro#7]
The method MatchTemplate() throws 'out of memory' exception in my computer. I don't really understand why, but it depends of ratio of remote screen. It probably comes from 'System.Drawing'. Maybe the 'Hash' value make it appends.

Any idea to fix it ?

Above the code of my scene
```
    class pressStart : Scene
    {
        public override string Name => "Root : Press start";

        public static RectMap pressStartScreen = new RectMap()
        {
            Width = 929,
            Height = 529,
            Hash = 8584986722532864
        };

        public override bool Match(ScriptBase script)
        {
            /* DEBUG */
            int i = 0;
            try
            {
                for (i = 100; i != 0 && !script.MatchTemplate(pressStartScreen, i); i--) { }
            }
            catch (System.OutOfMemoryException e)
            {
                Console.WriteLine("{0} : Error Message = {1} (i = {5}, W = {2}, H = {3}, Hash = {4})", Name, e.Message, pressStartScreen.Width, pressStartScreen.Height, pressStartScreen.Hash, i);
                return false;
            }
            Console.WriteLine("{0} : i= {1} %", Name, i);
            System.Diagnostics.Debug.WriteLine("{0} : i= {1} %", Name, i);

            return script.MatchTemplate(pressStartScreen, 98);
        }

        public override void OnMatched(ScriptBase script) => script.Press(new DualShockState() { Cross = true });
    }
```

I'm a beginner in C#.

edit1 : This exception appends when resizing remote screen while playing macro.
edit2: maybe values Width and Height makes it appends.

**Comment by komefai** [comment]
Hi, the Out Of Memory Exception is thrown when MatchTemplate is trying to crop an image but the are is out of bounds. 

As you've mentioned in `edit :` it's caused by resizing remote play while the script is running. You should decide what resolution to use beforehand (default is 1024x768) and set it like this in the constructor of your script:

```csharp
Config.Name = "Your Script";
Config.TargetSize = new Size(1024, 768);
```

So when you press play on PS4 Macro it will automatically resize to 1024x768.
