### ISSUE TITLE
No Issue: Just an Amzing Program

### ISSUE THREAD

**Issue by baggypants71** [komefai/PS4Macro#74]
Hi, I am a complete beginner in VS and C# so please bare with me. Using komefai/PS4Macro library how do I add a delay between each button press?. I know you can use "int waitDelay = 100;" but this would apply the  same value to all presses. I wish to assign a value to each button individually. Could someone be kind enough to help me out?.

**Comment by Unebrion** [comment]
Press(new DualShockState() { Square = true });
Sleep(waitDelay);

I believe this is what you're asking for? The example will press square then wait for the time specified by waitDelay. You can also just pass a number in there.

**Comment by ps4macro19** [comment]
Press(new DualShockState() { Square = true });
Sleep(waitDelay);

I think this is what you're asking. You can also just pass a number for waitDelay if you want to.
