### ISSUE TITLE
Is this project dead? Not working properly with the latest remote play update.

### ISSUE THREAD

**Issue by KinDeDu** [komefai/PS4Macro#93]
A year has passed since the last update and I noticed that the program does not work properly with the latest version of remote play. Everything works except for macro recordings even if it recognizes the ps4 controller connected to the PC. I tried any solution posted on github but none of this solved my problem. So I hope the project has not been completely abandoned.

**Comment by KoRnBoy82** [comment]
Komefai is a student and was doing this part time. Sadly, I haven't recieved replies to my private messages even if I recieve all issues by email also. I'm no programmer.

**Comment by KinDeDu** [comment]
Nevermind. I found a way to make it work. I just had to download an older version of the remote play. Now record macros without problems.
I'm sorry you didn't get any more answers from him even he created a nice project. I hope that in the future it comes back to add new features.
However, I solved the problem. Now I can close the issue.
Thanks for the reply.

**Comment by KoRnBoy82** [comment]
What version did you used? Thank you.

**Comment by Crazydmd** [comment]
I downloaded the original PS Remote 4.5 whatever

> What version did you used? Thank you.

After downloading Link to PS5 Manually after staying you don't want to update. Settings > Remote Play > Link Device
